site_name: Category Theory through Math & Programming for Dummies

repo_name: Varvos/cattheor-prog
repo_url: https://github.com/Varvos/cattheor-prog/
site_url: https://varvos.github.io/cattheor-prog/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - assets/css/custom.css
  - assets/css/tabs.css

extra_javascript:
  - assets/js/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/random-color.js

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - awesome-pages

nav:
  - Introduction:
    - Preface: 'intro/index.md'
    - Informal Introduction: 'intro/introduction-to-category-theory.md'

  - Preliminaries:
    - preliminaries/index.md
    - Set Theory: 'preliminaries/set_theory.md'
    - Algebra: 'preliminaries/basic_algebra.md'

  - Basic Concepts:
    - Formal Definitions: 'basics/formal_definitions.md'
    - Morphisms: 'basics/morphisms.md'
    - Functors: 'basics/functors.md'

  - Advanced Topics:
    - Monads and Monoids:
      - Monads: 'advanced/monads.md'
      - Monoids: 'advanced/monoids.md'
      - Monoidal Categories: 'advanced/monoidal_categories.md'
      - Monads in Programming: 'advanced/monads_in_programming.md'
    - Higher Categories: 'advanced/higher_categories.md'
    - Topos Theory: 'advanced/topos_theory.md'

  - Category Theory and Machine Learning:
    - Intro: 'ml/index.md'
    - Topological Data Analysis: 'ml/tda.md'
    - Graph Neural Networks: 'ml/gnn.md'
    - Categorical Deep Learning: 'ml/catlearn.md'
